### ISSUE TITLE
Add support for documentation check in travis

### ISSUE THREAD

**Issue by rande** [sonata-project/SonataDoctrineMongoDBAdminBundle#106]
It will be great if you can apply this patch https://github.com/sonata-project/SonataMediaBundle/commit/760c81c995491adb62f4a29c132eab284b0c7280 to this repository so we can validate the documentation.

You can install the sphinx tools with:

```
cd Resources/doc
sudo pip -r requirements.txt
```

and check that the documentation is generating correctly with the command

```
make html
```

**Comment by core23** [comment]
Travis checks this now :)
