### ISSUE TITLE
Add docs for DocumentManager and QueryBuilder usage

### ISSUE THREAD

**Issue by webdevilopers** [sonata-project/SonataDoctrineMongoDBAdminBundle#118]
Analog to the DoctrineORMAdminBundle
http://sonata-project.org/bundles/doctrine-orm-admin/master/doc/reference/query_proxy.html
there is an entry for MongoDBAdminBundle
http://sonata-project.org/bundles/mongo-admin/master/doc/reference/query_proxy.html

But I don't know if the usage of

``` php
$queryBuilder = $this->em->createQueryBuilder();
```

is correct for the ODM.

Anyway what still is missing (in the other bundle too BTW:
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/master/Resources/doc/reference/list_field_definition.rst
)
is an example for the `QueryBuilder` usage for filter types like `doctrine_mongo_choice` e.g.:

``` php
    protected function configureDatagridFilters(DatagridMapper $datagridMapper)
    {
        $builder = $this->getModelManager()
                        ->getDocumentManager('Sps\Bundle\CrmBundle\Document\HistoryType')
//                        ->getDocumentManager()
                        ->createQueryBuilder('Sps\Bundle\CrmBundle\Document\HistoryType');

        $types = $builder
                ->select('name', 'slug')
                ->hydrate(false)
                ->getQuery()
                ->execute();

        $typeChoices = array();
        foreach ($types as $type) {
            $typeChoices[$type['slug']] = $type['name'];
        }

        $datagridMapper
            ->add('type', 'doctrine_mongo_choice', array(),
                    'choice',
                    array('choices' => $typeChoices)
            )
        ;
    }
```

I havn't found any docs on this yet so I don't know if my attempt is best practice.

Can somebody comment on this and where I should create a PR with updated docs e.g.:
https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle/blob/master/Resources/doc/reference/list_field_definition.rst

**Comment by joshlopes** [comment]
@webdevilopers just saw this -- if not to late you are doing it right! you can however omit the second class on createQueryBuilder here goes one similar example:

````
$modelManager = $this->getModelManager();
$builder = $modelManager->getDocumentManager('ProductBundle:Types')->createQueryBuilder();

$types = $builder->hydrate(false)->select('name', 'slug')->getQuery()->execute();
````

:+1:

**Comment by webdevilopers** [comment]
Not too late @dunglas . Didn't work on the related project so far. Are you interested in adding the full example into the docs and create a PR?

**Comment by dunglas** [comment]
I would be nice. cc @rande

**Comment by core23** [comment]
Feel free to create a PR for the doc improvement. @webdevilopers

**Comment by webdevilopers** [comment]
I explained to @core23 on Twitter that I no longer maintain the projects that use Sonata.
I will try to comment on the issues anyway. I will close them if nobody else suggested a PR or similar.
