### ISSUE TITLE
What about inherit SonataDoctrineORMAdminBundle?

### ISSUE THREAD

**Issue by spolischook** [sonata-project/SonataDoctrineMongoDBAdminBundle#127]
I found bug in association js, that already fixed in SonataDoctrineORMAdminBundle (pr is coming soon). So what about inherit some template, especially javascript templates, from SonataDoctrineORMAdminBundle?

**Comment by joshlopes** [comment]
:+1:  i just opened a issue where the templates are outdated on mongo

**Comment by joshlopes** [comment]
this bug with association is already fixed on our side as well on some of my PRs FTW -- maybe i could embed the Admin one not sure why i didnt do that if i go there anytime soon i will put it to the admin one

**Comment by jordisala1991** [comment]
We are already using templates from AdminBundle (same as orm or phpcr)
