### ISSUE TITLE
Sort by embedded field

### ISSUE THREAD

**Issue by atrigub** [sonata-project/SonataDoctrineMongoDBAdminBundle#143]
Hi!

There is problem with sort data by embedded field. I want to change method setSortBy in ProxyQuery base on $parentAssociationMappings.

Is it good solution? Maybe do you have better idea?

**Comment by joshlopes** [comment]
Can you show some code @atrigub ?

**Comment by atrigub** [comment]
@joshlopes  I created pull request.
