### ISSUE TITLE
EmbedOne: How to configureFormFields ? 

### ISSUE THREAD

**Issue by acrozes** [sonata-project/SonataDoctrineMongoDBAdminBundle#152]
When I use `->add('user.name')` I have an error: 
`No mapping found for field 'user__name' in class '..\Document\Account'.`

But the mapping is in the embed class, called in my case as EmbedUser ...

``` php
class Account
{
    /**
     * @MongoDB\Id
     */
    protected $id;

    /**
     * @MongoDB\EmbedOne(targetDocument="EmbedUser")
     */
    protected $user;
[...]
```

**Comment by acrozes** [comment]
Also in configureDatagridFilters and in configureListFields ->add('user.name') no generate any error but filter and sort doesn't work because the query try to do it on the account fields, instead of on the EmbedUser fields

**Comment by nicodmf** [comment]
Same question
