### ISSUE TITLE
Is this bundle compatible with admin 3.0 (old 2.4)?

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/SonataDoctrineMongoDBAdminBundle#162]
I see you still require admin-bundle `~2.3`.

I would like, like for another bundles, make a new major supporting admin-bundle 3.0 and make 2.x legacy.

Is this bundle already tested for 3.0 which was the old 2.4.x-dev?

cc @dbu @lsmith77 @EmmanuelVella

**Comment by dunglas** [comment]
AFAIK it isn't.

**Comment by phofmann-trust** [comment]
We are using it with 2.4-dev from February this year. Works for us. Didn't try with 3.0 yet.

**Comment by acrozes** [comment]
For me it is ok with this pull request: https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle/pull/154

**Comment by dbu** [comment]
@Soullivaneuh I have nothing to do with this bundle. and afaik lukas neither. (no big deal, just saying so you know)

**Comment by Soullivaneuh** [comment]
> @Soullivaneuh I have nothing to do with this bundle. and afaik lukas neither. (no big deal, just saying so you know)

@dbu well, I found you on the collaborators list. :stuck_out_tongue: 

![image](https://cloud.githubusercontent.com/assets/1698357/15173582/25a8c4b6-175d-11e6-9df3-4d8414002492.png)

**Comment by Soullivaneuh** [comment]
> For me it is ok with this pull request: #154

@acrozes  All I can see on this PR is the locking of admin-bundle to 2.3 only, not 2.4/3.0...

**Comment by acrozes** [comment]
@Soullivaneuh : the render tag to function in twig template

**Comment by Soullivaneuh** [comment]
@acrozes I'm talking about **admin-bundle** compatibility, not Symfony.

**Comment by acrozes** [comment]
@Soullivaneuh: ok

**Comment by EmmanuelVella** [comment]
Hi, to be honest I don't use this bundle since a long time now, so can't say.

**Comment by Soullivaneuh** [comment]
Well, I'll start by making a 2.x branch and integrate dev-kit.

After that, I'll check if admin-bundle integration is covered by test. If yes, we will quickly see if this bundle is compatible or not.
