### ISSUE TITLE
Problem with "unexpected render tag"

### ISSUE THREAD

**Issue by dajuam** [sonata-project/SonataDoctrineMongoDBAdminBundle#181]
Hi, I'm having this problem:

Unexpected "render" tag (expecting closing tag for the "if" tag defined near line 54) in SonataDoctrineMongoDBAdminBundle:Form:form_admin_fields.html.twig at line 54.

When I access into creation admin page (/create). I am using Symfony 3.1 and the configuration in my composer.json is:

"doctrine/mongodb-odm": "^1.0",
"doctrine/mongodb": "~1.2",
"doctrine/mongodb-odm-bundle": "^3.1",
"sonata-project/doctrine-mongodb-admin-bundle": "dev-master"

I can fix it by commenting the "render" line, but I think you must know this problem.

Thank you very much.

**Comment by greg0ire** [comment]
Can you try replacing the render tag with the render function ? IIRC, one has been deprecated in favor of the other. If it works, can you provide a PR?

**Comment by dajuam** [comment]
Yes, of course.

**Comment by jeantristan** [comment]
I've got the same issue with:
        "sonata-project/admin-bundle": "^3.4@dev",
        "sonata-project/doctrine-mongodb-admin-bundle": "^3.0@dev",

What render function are you talking about?

**Comment by greg0ire** [comment]
> What render function are you talking about?

The one @dajuam uses in #182 (he literally removes the render tag and replaces it with the render function.

**Comment by greg0ire** [comment]
Closed in favor of #188
