### ISSUE TITLE
Update Bugs Hash type for core23

### ISSUE THREAD

**Issue by foji2** [sonata-project/SonataDoctrineMongoDBAdminBundle#234]
in the docs 👍

namespace Acme\AcmeBundle\Admin;

class UserAdmin extends Admin
{
    protected function configureListFields(ListMapper $listMapper)
    {
        $listMapper
            ->addIdentifier('id')
            ->add('firstName')
            ->add('lastName')
            ->add('address.street')
            ->add('address.ZIPCode')
            ->add('address.town')
        ;
    }
}
So why this not work for me ?

I have a document Place : 

```
    /**
     * @MongoDB\Field(name="address", type="hash")
     */
    protected $address;


{ 
    "_id" : ObjectId("4864765465465"), 
    "address" : {
        "postal_code" : "01300", 
        "street" : "av. Test", 
        "city" : "Test", 
        "country" : "France"
    }, 
    "name" : "test", 
    "state" : NumberInt(0), 
    "coordinates" : {
        "longitude" : 45.21, 
        "latitude" : 5.6136
    }
}
```

I want use Field Hash

```
    protected function configureListFields(ListMapper $listMapper)
    {
        $listMapper->addIdentifier('name', 'text', array('label' => 'Name'));
        $listMapper->addIdentifier('address.street');
        $listMapper->addIdentifier('state', 'text', array('label' => 'State'));
    }
```

But this not work i check log and got : 

```
request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Notice: Undefined index: address" at /var/www/html/dev/myproject/vendor/sonata-project/doctrine-mongodb-admin-bundle/Sonata/DoctrineMongoDBAdminBundle/Model/ModelManager.php line 69
```
It s the same as docs 

How i can do that ? 

Thanks

**Comment by core23** [comment]
Again...

We try to keep github issues for feature requests and bugs only. 

Please have a look at the [docs](https://sonata-project.org/bundles/) or use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and questions.

**Comment by jlamur** [comment]
This is probably related: https://github.com/sonata-project/SonataAdminBundle/issues/4671
