### ISSUE TITLE
Unexpected identifier in edit_mongo_one_association_script.html.twig

### ISSUE THREAD

**Issue by SouthOfWest** [sonata-project/SonataDoctrineMongoDBAdminBundle#248]
https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle/blob/cd75d22284490c2b287b403e42a33aafa1b6a5cd/src/Resources/views/CRUD/edit_mongo_one_association_script.html.twig#L55

  var id = '#'$(this).attr('id');

**Comment by core23** [comment]
Please provide a *little* more information.

Feel free to reopen when using the issue template.
