### ISSUE TITLE
Type error: trim() expects parameter 1 to be string, null given when adding DatagridFilters

### ISSUE THREAD

**Issue by psytraxx** [sonata-project/SonataDoctrineMongoDBAdminBundle#268]
### Environment

Docker Alpine Linux 3.4 - Nginx , PHP-FPM

#### Sonata packages

sonata-project/admin-bundle                  3.30.0             3.30.0             The missing Symfony Admin Generator
sonata-project/block-bundle                  3.9.0              3.9.0              Symfony SonataBlockBundle
sonata-project/cache                         2.0.1              2.0.1              Cache library
sonata-project/core-bundle                   3.8.0              3.8.0              Symfony SonataCoreBundle
sonata-project/datagrid-bundle               2.3.1              2.3.1              Symfony SonataDatagridBundle
sonata-project/doctrine-mongodb-admin-bundle dev-master 186bbc4 dev-master 186bbc4 Symfony Sonata / Integrate Doctrine MongoDB ODM into the SonataAdminBundle
sonata-project/exporter                      1.8.0              1.8.0              Lightweight Exporter library

#### Symfony packages

symfony/asset                v4.0.2  v4.0.2  Symfony Asset Component
symfony/browser-kit          v4.0.2  v4.0.2  Symfony BrowserKit Component
symfony/cache                v4.0.2  v4.0.2  Symfony Cache component with PSR-6, PSR-16, and tags
symfony/class-loader         v3.4.2  v3.4.2  Symfony ClassLoader Component
symfony/config               v4.0.2  v4.0.2  Symfony Config Component
symfony/console              v4.0.2  v4.0.2  Symfony Console Component
symfony/css-selector         v4.0.2  v4.0.2  Symfony CssSelector Component
symfony/debug                v4.0.2  v4.0.2  Symfony Debug Component
symfony/debug-bundle         v4.0.2  v4.0.2  Symfony DebugBundle
symfony/dependency-injection v4.0.2  v4.0.2  Symfony DependencyInjection Component
symfony/doctrine-bridge      v4.0.2  v4.0.2  Symfony Doctrine Bridge
symfony/dom-crawler          v4.0.2  v4.0.2  Symfony DomCrawler Component
symfony/dotenv               v4.0.2  v4.0.2  Registers environment variables from a .env file
symfony/event-dispatcher     v4.0.2  v4.0.2  Symfony EventDispatcher Component
symfony/expression-language  v4.0.2  v4.0.2  Symfony ExpressionLanguage Component
symfony/filesystem           v4.0.2  v4.0.2  Symfony Filesystem Component
symfony/finder               v4.0.2  v4.0.2  Symfony Finder Component
symfony/flex                 v1.0.53 v1.0.53
symfony/form                 v4.0.2  v4.0.2  Symfony Form Component
symfony/framework-bundle     v4.0.2  v4.0.2  Symfony FrameworkBundle
symfony/http-foundation      v4.0.2  v4.0.2  Symfony HttpFoundation Component
symfony/http-kernel          v4.0.2  v4.0.2  Symfony HttpKernel Component
symfony/inflector            v4.0.2  v4.0.2  Symfony Inflector Component
symfony/intl                 v4.0.2  v4.0.2  A PHP replacement layer for the C intl extension that includes additional data from the ICU library.
symfony/monolog-bridge       v4.0.2  v4.0.2  Symfony Monolog Bridge
symfony/monolog-bundle       v3.1.2  v3.1.2  Symfony MonologBundle
symfony/options-resolver     v4.0.2  v4.0.2  Symfony OptionsResolver Component
symfony/phpunit-bridge       v4.0.2  v4.0.2  Symfony PHPUnit Bridge
symfony/polyfill-apcu        v1.6.0  v1.6.0  Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu    v1.6.0  v1.6.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring    v1.6.0  v1.6.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php56       v1.6.0  v1.6.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70       v1.6.0  v1.6.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-php72       v1.6.0  v1.6.0  Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-util        v1.6.0  v1.6.0  Symfony utilities for portability of PHP codes
symfony/process              v4.0.2  v4.0.2  Symfony Process Component
symfony/property-access      v4.0.2  v4.0.2  Symfony PropertyAccess Component
symfony/routing              v4.0.2  v4.0.2  Symfony Routing Component
symfony/security             v3.4.2  v4.0.2  Symfony Security Component
symfony/security-acl         v3.0.0  v3.0.0  Symfony Security Component - ACL (Access Control List)
symfony/security-bundle      v4.0.2  v4.0.2  Symfony SecurityBundle
symfony/stopwatch            v4.0.2  v4.0.2  Symfony Stopwatch Component
symfony/swiftmailer-bundle   v3.1.6  v3.1.6  Symfony SwiftmailerBundle
symfony/templating           v4.0.2  v4.0.2  Symfony Templating Component
symfony/translation          v4.0.2  v4.0.2  Symfony Translation Component
symfony/twig-bridge          v4.0.2  v4.0.2  Symfony Twig Bridge
symfony/twig-bundle          v4.0.2  v4.0.2  Symfony TwigBundle
symfony/validator            v4.0.2  v4.0.2  Symfony Validator Component
symfony/var-dumper           v4.0.2  v4.0.2  Symfony mechanism for exploring and dumping PHP variables
symfony/web-link             v4.0.2  v4.0.2  Symfony WebLink Component
symfony/web-profiler-bundle  v4.0.2  v4.0.2  Symfony WebProfilerBundle
symfony/web-server-bundle    v4.0.2  v4.0.2  Symfony WebServerBundle
symfony/yaml                 v4.0.2  v4.0.2  Symfony Yaml Component

#### PHP version

PHP 7.1.9 (cli) (built: Oct  2 2017 20:51:54) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.9, Copyright (c) 1999-2017, by Zend Technologies

## Subject

this was working with symfony 3.4.x and only breaks now after to upgrade to symfony 4.02
when i remove the datagrid filters sonata admin method everything works as usual but there are no filters ..

I can fix this in

namespace Sonata\DoctrineMongoDBAdminBundle\Filter;

use Sonata\AdminBundle\Datagrid\ProxyQueryInterface;
use Sonata\AdminBundle\Form\Type\Filter\ChoiceType;

class StringFilter extends Filter 

    public function filter(ProxyQueryInterface $queryBuilder, $name, $field, $data): void
    {
        if (!$data  || !is_array($data) || !array_key_exists('value', $data) || $data['value'] == null) {
            return;
        }

PR [https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle/pull/267](https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle/pull/267)

## Steps to reproduce

add a datafilter

    // Fields to be shown on filter forms
    protected function configureDatagridFilters(DatagridMapper $datagridMapper)
    {
        $datagridMapper
            ->add('title', StringFilter::class)
            ->add('pageid', StringFilter::class);
    }

## Expected results

Filter Renders the two fields pageid and title

## Actual results

Symfony\Component\Debug\Exception\FatalThrowableError:
Type error: trim() expects parameter 1 to be string, null given

  at vendor/sonata-project/doctrine-mongodb-admin-bundle/src/Filter/StringFilter.php:33
  at trim(null)
     (vendor/sonata-project/doctrine-mongodb-admin-bundle/src/Filter/StringFilter.php:33)
  at Sonata\DoctrineMongoDBAdminBundle\Filter\StringFilter->filter(object(ProxyQuery), null, 'title', array('type' => null, 'value' => null))
     (vendor/sonata-project/doctrine-mongodb-admin-bundle/src/Filter/Filter.php:29)
  at Sonata\DoctrineMongoDBAdminBundle\Filter\Filter->apply(object(ProxyQuery), array('type' => null, 'value' => null))
     (vendor/sonata-project/admin-bundle/src/Datagrid/Datagrid.php:141)
  at Sonata\AdminBundle\Datagrid\Datagrid->buildPager()
     (vendor/sonata-project/admin-bundle/src/Datagrid/Datagrid.php:261)
  at Sonata\AdminBundle\Datagrid\Datagrid->getForm()
     (vendor/sonata-project/admin-bundle/src/Controller/CRUDController.php:157)
  at Sonata\AdminBundle\Controller\CRUDController->listAction()
     (vendor/symfony/http-kernel/HttpKernel.php:149)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:66)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:190)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (public/app.php:34)

**Comment by psytraxx** [comment]
thanks for the quick merge for my PR and the help to resolve this issue @greg0ire

**Comment by greg0ire** [comment]
You're welcome!
