### ISSUE TITLE
Form/Filter Templates broken with admin 3.98.2

### ISSUE THREAD

**Issue by dmaicher** [sonata-project/SonataDoctrineMongoDBAdminBundle#583]
Similar to https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1427 we need to make sure we merge the `setFormTheme` and `setFilterTheme` calls as now on Sonata admin 3.98.2+ we are adding those calls as well.

So currently the templates of this bundle are not properly configured anymore when using admin bundle 3.98.2+.

**Comment by VincentLanglet** [comment]
Can you open the PR @dmaicher ?
