### ISSUE TITLE
Embed array and Embed Collection are not shown on admin interface

### ISSUE THREAD

**Issue by zeitnot** [sonata-project/SonataDoctrineMongoDBAdminBundle#62]
I am getting crazy becausefe of the lack of enough knowledge about sonata admin and of course SonataDoctrineMongoDBAdminBundle. Firstly, I have installed SonataUserBundle and everything works well except user groups. To run the interface correctly, I need to comment all abput groups.

So to run without errors my final UserAdmin file is like this. http://pastebin.com/DNM8kf6V

If  I remove comments before on groups when edit or add new user then an exception occurs such as:

```
Class '' does not exists
```

 When I use SonataDoctrineORMAdminBundle there is no any problem. Everyting runs like http://demo.sonata-project.org/admin/dashboard

When I read the documentation, everything is about Doctrine ORM. There is no sufficient documentation for mongodb users. I have wasted about 15 days on this issue. But I could not find any solution. This is getting me so nervous. Would you recommend me a good installaition guide for mongodb? I really need some guru's help.

**Comment by joshlopes** [comment]
I just saw this and i remember having some troubles with it to.. but now everything is okay on my side probably i went and disabled the group settings as well -- can anyone confirm that this is still a problem of DoctrineMongoDB ? maybe i can fix it if i know this is still happening. Spam Ping @zeitnot @KingCrunch @danielsan @lennerd

**Comment by zeitnot** [comment]
@joostfarla I migrated to rails :)

**Comment by jacobchristensen79** [comment]
This is still an Issue, in order to fix it I had to change a few lines:
edit_mongo_one.html.twig  where on line 54 Render is in {% render and not {{ render...
same for 
form_admin_fields.html.twig on line 48

**Comment by greg0ire** [comment]
@jacobchristensen79 : would you kindly provide a PR for that?

**Comment by jacobchristensen79** [comment]
Hi gregOire, sorry, I just saw that in 02ba928b4912c62578b6a09a633b89ce3c9365af jeantristan fixed the render tag.  I had this as pending since last month. 
About the Embedded and array, I'll check it out as I think I have some cases where I use it.  sorry.

**Comment by greg0ire** [comment]
Oh right, this looked familiar indeed, but I thought it must have been about another bundle. But there hasn't been a release since then apparently.

**Comment by jacobchristensen79** [comment]
When do you plan to tag admin-bundle so it pulls the last "fixes" for this "render" issue?
Specially the edit_mongo_one.html.twig
line 27,      {% render url('sonata_admin_short_object_information', {  ...
thanks a lot :)

**Comment by greg0ire** [comment]
As soon as [this situation](https://github.com/sonata-project/dev-kit/pull/192) is resolved I think.

**Comment by jacobchristensen79** [comment]
Hello, 
As I said before I would have a look, I use MongoDB to, I managed to have the groups, in this case we had a User with a array list of Customer ID's ( long story, .. )

In the "admin":
`->add(
                'customer',
                'sonata_type_collection',
                ['label' => 'Customer Ids'],
                [
                    'edit' => 'inline',
                    'inline' => 'table',
                    'sortable' => 'position'
                ]
            )`

and this render perfect. 
customer is in User collection:
Doctrine\Common\Collections\ArrayCollection

But in order to render the page you need also a 
class CustomerAdmin extends Admin
...
` $formMapper
            ->with('Customer Ids')
                ->add('id', 'text')
            ->end();`

If you need the full code, please ping me.

**Comment by jordisala1991** [comment]
This doesnt seem to belong here. Closing, if the issue it is still relevant and want to reopen just ping me
